http_server:
  address: ":8080"
rabbit_mq:
  host: "rabbitMQ"
  port: 5672
  queue_name: "testQueue"
postgres_db:
  host: "postgres"
  port: 5432
  db_name: "postgres_db"
  sslmode: "disable"
  dir: repository/postgres/psql_migrations
redis_db:
  address: "redis:6379"
  default_password: "password"
  db_number: 0
  duration: 24h